var database = null;

database = db.getMongo().getDB('QuestorEdoc08651809000195');
database.getCollection('Nfe').createIndex({ Number: 1 },{ background: true})
database.getCollection('Nfe').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Key: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Client._id: 1 },{ background: true})

database = db.getMongo().getDB('QuestorEdoc08825817000100');
database.getCollection('Nfe').createIndex({ Number: 1 },{ background: true})
database.getCollection('Nfe').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Key: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Client._id: 1 },{ background: true})

database = db.getMongo().getDB('QuestorEdoc17425174000107');
database.getCollection('Nfe').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Key: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Client._id: 1 },{ background: true})

database = db.getMongo().getDB('QuestorEdoc17804753000152');
database.getCollection('Nfe').createIndex({ Number: 1 },{ background: true})
database.getCollection('Nfe').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Key: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Client._id: 1 },{ background: true})

database = db.getMongo().getDB('QuestorEdoc24519969000131');
database.getCollection('Nfe').createIndex({ Number: 1 },{ background: true})
database.getCollection('Nfe').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Key: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Client._id: 1 },{ background: true})

database = db.getMongo().getDB('QuestorEdoc77500346000183');
database.getCollection('Nfe').createIndex({ Number: 1 },{ background: true})
database.getCollection('Nfe').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Key: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Nfce').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cte').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cteos').createIndex({ Client._id: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Key: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Category._id: 1 },{ background: true})
database.getCollection('Cfe').createIndex({ Client._id: 1 },{ background: true})


//Indexes para adicionar no arquivo de instalação de bases do Zen
//CreateIndex('Nfce', 'DhEmi');
